select * from customer limit 20


--Q1. what is the total revenue generated by male vs female customer?

select gender, SUM(purchase_amount) as revenue
from customer
group by gender

--Q2. Which customers used a discount but still spent more than the avarage purchase amount.?
select customer_id, purchase_amount
from customer
where discount_applied = 'Yes' and purchase_amount >= (select avg(purchase_amount) from customer)

--Q3. Which are the top 5 products with the highest average review rating?

SELECT item_purchased,
       round(AVG(review_rating)::numeric,2) AS avg_rating
FROM customer
GROUP BY item_purchased             --count is aggregate function so we use group by
ORDER BY avg(review_rating) DESC
LIMIT 5;

--Q4. Compare the average purchase amounts between standard and express shipping

select shipping_type,
        round(avg(purchase_amount),2) as "average purchase amount"
from customer
where shipping_type in ('Standard','Express')
group by shipping_type

--Q5. Do subscribed customers spend more? compare average spend and total revenue between
--subscribers and non-subscribers?

select subscription_status,
       count(customer_id) as total_customers,
	   round(avg(purchase_amount),2) as avg_spent,
       round(sum(purchase_amount),2) as total_revenue
from customer
group by subscription_status
order by total_revenue, avg_spent desc;

--Q6. which 5 products have the highest percentage of purchases with discounts applied?

select item_purchased, round(100 * sum(case when discount_applied = 'Yes' then 1 else 0 end)/count(*),2) as discount_rate
from customer
group by item_purchased
order by discount_rate desc
limit 5;

--Q7. segment customers into new , returning , and loyal based on their total
--number of previous purchases , and show the count of each segment.

with customer_type as (
select customer_id, previous_purchases,
case
    when previous_purchases = 1 then 'New'
	when previous_purchases between 2 and 10 then 'Returning'
	else 'loyal'
	end as customer_segment
from customer
)

select customer_segment, count(*) as "Number of customers"
from customer_type
group by customer_segment

--Q8. What are the top 3 most purchased products with in each category?

SELECT item_rank,
       category,
       item_purchased,
       purchase_count
FROM (
    SELECT category,
           item_purchased,
           COUNT(*) AS purchase_count,
           ROW_NUMBER() OVER (PARTITION BY category
                        ORDER BY COUNT(*) DESC) AS item_rank
    FROM customer
    GROUP BY category, item_purchased
) ranked
WHERE item_rank <= 3;

--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

select subscription_status,
count(customer_id) as repeat_buyers
from customer
where previous_purchases > 5
group by subscription_status

--Q10. what is the revenue contribution of each age group?
select age_group, sum(purchase_amount) as total_revenue
from customer
group by age_group
order by total_revenue desc;